### ISSUE TITLE
Hsd has exited unexpectedly

### ISSUE THREAD

**Issue by PicaroonEsp** [HyperspaceApp/Hyperspace#29]
Wallet: scanned to height 14286...
Wallet: scanned to height 14286...
Wallet: scanned to height 14286...
Done!
goroutine 359200 [running]:
runtime/debug.Stack(0x4466ee, 0x0, 0xc0012b3a80)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x29
github.com/HyperspaceApp/Hyperspace/build.Critical(0xc0012b3c28, 0x1, 0x1)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/build/critical.go:16 +0x9a
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).HeaderConsensusSetSubscribe(0xc00016e780, 0xd91600, 0xc0000e0480, 0xd166caed534ca852, 0x58cd23fac1e4c815, 0x92f442a4a4964137, 0x6b29a567aae4d4de, 0xc00004aae0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/spv_subscribe.go:84 +0x502
github.com/HyperspaceApp/Hyperspace/modules/wallet.(*Wallet).managedUnlock(0xc0000e0480, 0xd9a7e0, 0xc000841d60, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/wallet/encrypt.go:244 +0x3fc
github.com/HyperspaceApp/Hyperspace/modules/wallet.(*Wallet).Unlock(0xc0000e0480, 0xd9a7e0, 0xc000841d60, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/wallet/encrypt.go:498 +0x151
github.com/HyperspaceApp/Hyperspace/node/api.(*API).walletUnlockHandler(0xc00011c0f0, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/wallet.go:715 +0xc6
github.com/HyperspaceApp/Hyperspace/node/api.(*API).walletUnlockHandler-fm(0xd97ce0, 0xc0007217a0, 0xc0004d6d00, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:184 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0001b23c0, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/Users/mark/.go/src/github.com/julienschmidt/httprouter/router.go:334 +0x799
github.com/HyperspaceApp/Hyperspace/node/api.RequireUserAgent.func1(0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:238 +0xc2
net/http.HandlerFunc.ServeHTTP(0xc000690270, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/usr/local/opt/go/libexec/src/net/http/server.go:1964 +0x4b
github.com/HyperspaceApp/Hyperspace/node/api.cleanCloseHandler.func1.1(0xc000fa8d20, 0xd92a80, 0xc000690270, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:209 +0x80
created by github.com/HyperspaceApp/Hyperspace/node/api.cleanCloseHandler.func1
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:207 +0xa7
Critical error: refusing to double-subscribe subscriber
Please submit a bug report here: https://github.com/HyperspaceApp/Hyperspace/issues
goroutine 359200 [running]:
runtime/debug.Stack(0x4466ee, 0x0, 0xc0012b39b8)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x29
github.com/HyperspaceApp/Hyperspace/build.Critical(0xc0012b3b60, 0x1, 0x1)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/build/critical.go:16 +0x9a
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).HeaderConsensusSetSubscribe(0xc00016e780, 0xd915c0, 0xc000fd9ce0, 0xd166caed534ca852, 0x58cd23fac1e4c815, 0x92f442a4a4964137, 0x6b29a567aae4d4de, 0xc000231380, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/spv_subscribe.go:84 +0x502
github.com/HyperspaceApp/Hyperspace/modules/transactionpool.(*TransactionPool).StartSubscribeHeaders(0xc000fd9ce0, 0xd91601, 0xc0000e0480)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/transactionpool/update_header.go:208 +0x10c
github.com/HyperspaceApp/Hyperspace/modules/wallet.(*Wallet).managedUnlock(0xc0000e0480, 0xd9a7e0, 0xc000841d60, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/wallet/encrypt.go:269 +0x518
github.com/HyperspaceApp/Hyperspace/modules/wallet.(*Wallet).Unlock(0xc0000e0480, 0xd9a7e0, 0xc000841d60, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/wallet/encrypt.go:498 +0x151
github.com/HyperspaceApp/Hyperspace/node/api.(*API).walletUnlockHandler(0xc00011c0f0, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/wallet.go:715 +0xc6
github.com/HyperspaceApp/Hyperspace/node/api.(*API).walletUnlockHandler-fm(0xd97ce0, 0xc0007217a0, 0xc0004d6d00, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:184 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0001b23c0, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/Users/mark/.go/src/github.com/julienschmidt/httprouter/router.go:334 +0x799
github.com/HyperspaceApp/Hyperspace/node/api.RequireUserAgent.func1(0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:238 +0xc2
net/http.HandlerFunc.ServeHTTP(0xc000690270, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/usr/local/opt/go/libexec/src/net/http/server.go:1964 +0x4b
github.com/HyperspaceApp/Hyperspace/node/api.cleanCloseHandler.func1.1(0xc000fa8d20, 0xd92a80, 0xc000690270, 0xd97ce0, 0xc0007217a0, 0xc0004d6d00)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:209 +0x80
created by github.com/HyperspaceApp/Hyperspace/node/api.cleanCloseHandler.func1
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/node/api/routes.go:207 +0xa7
Critical error: refusing to double-subscribe subscriber
Please submit a bug report here: https://github.com/HyperspaceApp/Hyperspace/issues
panic: Consensus change series appears to be inconsistent - we are applying the wrong block. pid: 00000000000000063f217e1df52a00d5f2e2f15d7d57885cdb9c203b1ebcb0e0 recent: 000000000000000201f8489c059af03c25674876a15b988a424b999c0db22616

goroutine 359809 [running]:
github.com/HyperspaceApp/Hyperspace/modules/transactionpool.(*TransactionPool).ProcessHeaderConsensusChange(0xc000fd9ce0, 0xf3b2c774341f3cec, 0xa3b0daf5903c2728, 0x4fe6a45284ee3a52, 0xb6f132a5fcca5fd8, 0x0, 0x0, 0x0, 0xc000aab440, 0x1, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/transactionpool/update_header.go:48 +0x2076
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).updateHeaderSubscribers(0xc00016e780, 0x0, 0x0, 0x0, 0xc000da9860, 0x1, 0x1)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/spv_subscribe.go:31 +0x22f
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedAcceptHeaders(0xc00016e780, 0xc000ec3f08, 0x1, 0x1, 0x136a400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/spv_accept.go:223 +0x56f
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader.func5(0xc000ab92d0, 0xc00016e780, 0xd9cf00, 0xc002b0af60, 0xc000604c60, 0xc0000a1040, 0xc000735750)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/synchronize.go:482 +0x150
created by github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/synchronize.go:476 +0x491

**Comment by huetsch** [comment]
@PicaroonEsp what version of Hyperspace was this? Are you able to reproduce it on v0.2.3?

**Comment by monjere** [comment]
Ive had the same issue on v 0.2.3 - though i could not close and then open from exe file. I had to go back to the previous version ( after going through numerous other versions first ) . Strange issue. All was running normally till one night when the Hsd issue reared its ugly litle head.

Issue i had:
My wallet crashed for some reason when i opened it and i am now getting an error message - Hsd not found Hyperspace could not locate Hsd. please navigate to hsd - Any ideas on how to retrieve.... thx...{ then located/navigated to  hsd and clicked on  it and got - A critical error loading Hyperspace has occurred. ERROR Spawn UNKNOWN...
