### ISSUE TITLE
Hsd Has Exited Unexpectedly

### ISSUE THREAD

**Issue by stuffoflegends** [HyperspaceApp/Hyperspace#30]
Hyperspace Daemon v0.2.2
Git Revision 4ea4096f6
Loading...
listen tcp 127.0.0.1:5580: bind: Only one usage of each socket address (p(3/6) Loading transaction pool...
Received an invalid block set.
(4/6) Loading wallet...
(5/6) Loading host...
goroutine 1 [running]:
runtime/debug.Stack(0x4466ee, 0x0, 0xc000478070)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x29
github.com/HyperspaceApp/Hyperspace/build.Critical(0xc000478370, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/build/critical.go:16 +0x9a
github.com/HyperspaceApp/Hyperspace/persist.(*Logger).Critical(0xc0001f8140, 0xc000478370, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/persist/log.go:37 +0xd3
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc00017a500, 0xc00027eee0, 0x0, 0x0, 0x0, 0xc00025a7c0, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:49 +0x1112
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc00027eee0, 0xcbb858, 0xc00027eee0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:178 +0x19a
github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt.(*DB).View(0xc000266000, 0xc000478ed8, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt/db.go:708 +0x97
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc00017a500, 0xd91480, 0xc0000a4000, 0x6d29c81774fab49c, 0x7655b69cfbca82fe, 0x19837e424d91948a, 0xda85754009b4434b, 0xc000235980, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:170 +0x3e8
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc00017a500, 0xd91480, 0xc0000a4000, 0x6d29c81774fab49c, 0x7655b69cfbca82fe, 0x19837e424d91948a, 0xda85754009b4434b, 0xc000235980, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:227 +0xf8
github.com/HyperspaceApp/Hyperspace/modules/host.(*Host).initConsensusSubscription(0xc0000a4000, 0xc0004791c8, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/update.go:102 +0x8e
github.com/HyperspaceApp/Hyperspace/modules/host.(*Host).load(0xc0000a4000, 0xc000d40c00, 0xc0006af4a0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/persist.go:200 +0x3b7
github.com/HyperspaceApp/Hyperspace/modules/host.newHost(0xda0d60, 0xc000004740, 0xda0e20, 0xc00017a500, 0xd9e1c0, 0xc000170000, 0xd9dc00, 0xc0006af1e0, 0xda6120, 0xc000d4a000, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/host.go:292 +0x59b
github.com/HyperspaceApp/Hyperspace/modules/host.New(0xda0e20, 0xc00017a500, 0xd9e1c0, 0xc000170000, 0xd9dc00, 0xc0006af1e0, 0xda6120, 0xc000d4a000, 0xc00001a38c, 0x5, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/host.go:317 +0xee
main.(*Server).loadModules(0xc0000c66e0, 0xcbbef8, 0xc00004a480)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/server.go:562 +0x1976
main.startDaemon(0x0, 0x0, 0xc00001a34b, 0xe, 0xc00001e0fb, 0x5, 0xc00001a38c, 0x5, 0x0, 0xc00001e13a, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:268 +0x2ca
main.startDaemonCmd(0xc000103680, 0xc00009ea50, 0x0, 0x5)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:322 +0x1b4
github.com/spf13/cobra.(*Command).execute(0xc000103680, 0xc00007c010, 0x5, 0x7, 0xc000103680, 0xc00007c010)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000103680, 0xc821db, 0xf, 0xc00013ea00)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xc000103680, 0x1366018, 0xc6f695)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:800 +0x32
main.main()
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/main.go:197 +0x7ee
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist
Please submit a bug report here: https://github.com/HyperspaceApp/Hyperspace/issues
requested item does not exist

**Comment by stuffoflegends** [comment]
Closed and reopened and it properly loaded.
