### ISSUE TITLE
Hsd has exited unexpectedly.  v0.2.3 downloaded from website.  Recovery from v1 seed

### ISSUE THREAD

**Issue by GoldKimber-Mining** [HyperspaceApp/Hyperspace#46]
Hyperspace Daemon v0.2.3
Git Revision b121f350f
Loading...
(0/6) Loading hsd...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
goroutine 1 [running]:
runtime/debug.Stack(0x4466ee, 0x0, 0xc000078060)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x29
github.com/HyperspaceApp/Hyperspace/build.Critical(0xc000078360, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/build/critical.go:16 +0x9a
github.com/HyperspaceApp/Hyperspace/persist.(*Logger).Critical(0xc0001a7d00, 0xc000078360, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/persist/log.go:37 +0xd3
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc000162780, 0xc000fc2620, 0x0, 0x0, 0x0, 0xc001552b60, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:49 +0x1112
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc000fc2620, 0xcc1548, 0xc000fc2620)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:178 +0x19a
github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt.(*DB).View(0xc00010a780, 0xc000078ec8, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt/db.go:708 +0x97
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc000162780, 0xd98780, 0xc0000b2000, 0x6d29c81774fab49c, 0x7655b69cfbca82fe, 0x19837e424d91948a, 0xda85754009b4434b, 0xc001918ae0, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:170 +0x3e8
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc000162780, 0xd98780, 0xc0000b2000, 0x6d29c81774fab49c, 0x7655b69cfbca82fe, 0x19837e424d91948a, 0xda85754009b4434b, 0xc001918ae0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:227 +0xf8
github.com/HyperspaceApp/Hyperspace/modules/host.(*Host).initConsensusSubscription(0xc0000b2000, 0xc0000791b8, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/update.go:102 +0x8e
github.com/HyperspaceApp/Hyperspace/modules/host.(*Host).load(0xc0000b2000, 0xc000ee99c0, 0xc00023fe40)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/persist.go:200 +0x3b7
github.com/HyperspaceApp/Hyperspace/modules/host.newHost(0xda8340, 0xc000004720, 0xda8400, 0xc000162780, 0xda5560, 0xc0000d46e0, 0xda4fa0, 0xc00023fce0, 0xdad700, 0xc0000d6480, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/host.go:292 +0x59b
github.com/HyperspaceApp/Hyperspace/modules/host.New(0xda8400, 0xc000162780, 0xda5560, 0xc0000d46e0, 0xda4fa0, 0xc00023fce0, 0xdad700, 0xc0000d6480, 0xc00001c30c, 0x5, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/host/host.go:317 +0xee
main.(*Server).loadModules(0xc000003380, 0xcc1bf0, 0xc000058300)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/server.go:562 +0x1956
main.startDaemon(0x0, 0x0, 0xc00001c2cb, 0xe, 0xc0000200fb, 0x5, 0xc00001c30c, 0x5, 0x0, 0xc00002013a, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:276 +0x2bc
main.startDaemonCmd(0xc000111680, 0xc0000aca50, 0x0, 0x5)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:330 +0x19a
github.com/spf13/cobra.(*Command).execute(0xc000111680, 0xc00008c010, 0x5, 0x7, 0xc000111680, 0xc00008c010)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000111680, 0xc87fc7, 0xf, 0xc000152960)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xc000111680, 0x136f178, 0xc75469)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:800 +0x32
main.main()
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/main.go:197 +0x7ee
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist
Please submit a bug report here: https://github.com/HyperspaceApp/Hyperspace/issues
requested item does not exist

**Comment by monjere** [comment]
Ive had the same issue on v 0.2.3 - though i could not close and then open from exe file. I had to go back to the previous version ( after going through numerous other versions first ) . Strange issue. All was running normally till one night when the Hsd issue reared its ugly litle head.
